/*

 BOARD_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 21 x 18
   Tile set      : domination.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define DominationMapWidth 21
#define DominationMapHeight 18
#define DominationMapBank 0

extern unsigned char DominationMap[];

/* End of BOARD_MAP.H */
