/*

 START_SCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 19
   Tile set      : P:\Google Drive\03 Design\Games\Gameboy\domination.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define DominationStartScreenWidth 20
#define DominationStartScreenHeight 19
#define DominationStartScreenBank 0

extern unsigned char DominationStartScreen[];

/* End of START_SCREEN.H */
